/* File: fedrixsmodule.c
 * This file is auto-generated with f2py (version:1.21.2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Thu Nov  7 18:08:16 2024
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <string.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *fedrixs_error;
static PyObject *fedrixs_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef char * string;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
\
#define FAILNULL(p) do {                                            \
    if ((p) == NULL) {                                              \
        PyErr_SetString(PyExc_MemoryError, "NULL pointer found");   \
        goto capi_fail;                                             \
    }                                                               \
} while (0)

#define STRINGMALLOC(str,len)\
    if ((str = (string)malloc(sizeof(char)*(len+1))) == NULL) {\
        PyErr_SetString(PyExc_MemoryError, "out of memory");\
        goto capi_fail;\
    } else {\
        (str)[len] = '\0';\
    }

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define STRINGFREE(str) do {if (!(str == NULL)) free(str);} while (0)

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#define STRINGCOPYN(to,from,buf_size)                           \
    do {                                                        \
        int _m = (buf_size);                                    \
        char *_to = (to);                                       \
        char *_from = (from);                                   \
        FAILNULL(_to); FAILNULL(_from);                         \
        (void)strncpy(_to, _from, sizeof(char)*_m);             \
        _to[_m-1] = '\0';                                      \
        /* Padding with spaces instead of nulls */              \
        for (_m -= 2; _m >= 0 && _to[_m] == '\0'; _m--) {      \
            _to[_m] = ' ';                                      \
        }                                                       \
    } while (0)


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int
int_from_pyobj(int* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;

    if (PyLong_Check(obj)) {
        *v = Npy__PyLong_AsInt(obj);
        return !(*v == -1 && PyErr_Occurred());
    }

    tmp = PyNumber_Long(obj);
    if (tmp) {
        *v = Npy__PyLong_AsInt(tmp);
        Py_DECREF(tmp);
        return !(*v == -1 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj, 0);
    if (tmp) {
        PyErr_Clear();
        if (int_from_pyobj(v, tmp, errmess)) {
            Py_DECREF(tmp);
            return 1;
        }
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = fedrixs_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}

static int
string_from_pyobj(string *str,int *len,const string inistr,PyObject *obj,const char *errmess)
{
    PyArrayObject *arr = NULL;
    PyObject *tmp = NULL;
#ifdef DEBUGCFUNCS
fprintf(stderr,"string_from_pyobj(str='%s',len=%d,inistr='%s',obj=%p)\n",(char*)str,*len,(char *)inistr,obj);
#endif
    if (obj == Py_None) {
        if (*len == -1)
            *len = strlen(inistr); /* Will this cause problems? */
        STRINGMALLOC(*str,*len);
        STRINGCOPYN(*str,inistr,*len+1);
        return 1;
    }
    if (PyArray_Check(obj)) {
        if ((arr = (PyArrayObject *)obj) == NULL)
            goto capi_fail;
        if (!ISCONTIGUOUS(arr)) {
            PyErr_SetString(PyExc_ValueError,"array object is non-contiguous.");
            goto capi_fail;
        }
        if (*len == -1)
            *len = (PyArray_ITEMSIZE(arr))*PyArray_SIZE(arr);
        STRINGMALLOC(*str,*len);
        STRINGCOPYN(*str,PyArray_DATA(arr),*len+1);
        return 1;
    }
    if (PyBytes_Check(obj)) {
        tmp = obj;
        Py_INCREF(tmp);
    }
    else if (PyUnicode_Check(obj)) {
        tmp = PyUnicode_AsASCIIString(obj);
    }
    else {
        PyObject *tmp2;
        tmp2 = PyObject_Str(obj);
        if (tmp2) {
            tmp = PyUnicode_AsASCIIString(tmp2);
            Py_DECREF(tmp2);
        }
        else {
            tmp = NULL;
        }
    }
    if (tmp == NULL) goto capi_fail;
    if (*len == -1)
        *len = PyBytes_GET_SIZE(tmp);
    STRINGMALLOC(*str,*len);
    STRINGCOPYN(*str,PyBytes_AS_STRING(tmp),*len+1);
    Py_DECREF(tmp);
    return 1;
capi_fail:
    Py_XDECREF(tmp);
    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = fedrixs_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC_US(ed_fsolver,ED_FSOLVER)(int*,int*,int*,string,size_t);
extern void F_FUNC_US(ed_fsolver_intermediate,ED_FSOLVER_INTERMEDIATE)(int*,int*,int*,string,size_t);
extern void F_FUNC_US(xas_fsolver,XAS_FSOLVER)(int*,int*,int*,string,size_t);
extern void F_FUNC_US(rixs_fsolver,RIXS_FSOLVER)(int*,int*,int*,string,size_t);
extern void F_FUNC_US(opavg_fsolver,OPAVG_FSOLVER)(int*,int*,int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/********************************* ed_fsolver *********************************/
static char doc_f2py_rout_fedrixs_ed_fsolver[] = "\
ed_fsolver(comm,my_id,num_procs,[folder])\n\nWrapper for ``ed_fsolver``.\
\n\nParameters\n----------\n"
"comm : input int\n"
"my_id : input int\n"
"num_procs : input int\n"
"\nOther Parameters\n----------------\n"
"folder : input string(len=-1)";
/* extern void F_FUNC_US(ed_fsolver,ED_FSOLVER)(int*,int*,int*,string,size_t); */
static PyObject *f2py_rout_fedrixs_ed_fsolver(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,string,size_t)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

  int comm = 0;
  PyObject *comm_capi = Py_None;
  int my_id = 0;
  PyObject *my_id_capi = Py_None;
  int num_procs = 0;
  PyObject *num_procs_capi = Py_None;
  string folder = NULL;
  int slen(folder);
  PyObject *folder_capi = Py_None;
    static char *capi_kwlist[] = {"comm","my_id","num_procs","folder",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOO|O:fedrixs.ed_fsolver",\
        capi_kwlist,&comm_capi,&my_id_capi,&num_procs_capi,&folder_capi))
        return NULL;
/*frompyobj*/
  /* Processing variable comm */
    f2py_success = int_from_pyobj(&comm,comm_capi,"fedrixs.ed_fsolver() 1st argument (comm) can't be converted to int");
  if (f2py_success) {
  /* Processing variable my_id */
    f2py_success = int_from_pyobj(&my_id,my_id_capi,"fedrixs.ed_fsolver() 2nd argument (my_id) can't be converted to int");
  if (f2py_success) {
  /* Processing variable num_procs */
    f2py_success = int_from_pyobj(&num_procs,num_procs_capi,"fedrixs.ed_fsolver() 3rd argument (num_procs) can't be converted to int");
  if (f2py_success) {
  /* Processing variable folder */
  slen(folder) = -1;
  f2py_success = string_from_pyobj(&folder,&slen(folder),"",folder_capi,"string_from_pyobj failed in converting 1st keyword `folder' of fedrixs.ed_fsolver to C string");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&comm,&my_id,&num_procs,folder,slen(folder));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    STRINGFREE(folder);
  }  /*if (f2py_success) of folder*/
  /* End of cleaning variable folder */
  } /*if (f2py_success) of num_procs*/
  /* End of cleaning variable num_procs */
  } /*if (f2py_success) of my_id*/
  /* End of cleaning variable my_id */
  } /*if (f2py_success) of comm*/
  /* End of cleaning variable comm */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/***************************** end of ed_fsolver *****************************/

/************************** ed_fsolver_intermediate **************************/
static char doc_f2py_rout_fedrixs_ed_fsolver_intermediate[] = "\
ed_fsolver_intermediate(comm,my_id,num_procs,[folder])\n\nWrapper for ``ed_fsolver_intermediate``.\
\n\nParameters\n----------\n"
"comm : input int\n"
"my_id : input int\n"
"num_procs : input int\n"
"\nOther Parameters\n----------------\n"
"folder : input string(len=-1)";
/* extern void F_FUNC_US(ed_fsolver_intermediate,ED_FSOLVER_INTERMEDIATE)(int*,int*,int*,string,size_t); */
static PyObject *f2py_rout_fedrixs_ed_fsolver_intermediate(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,string,size_t)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

  int comm = 0;
  PyObject *comm_capi = Py_None;
  int my_id = 0;
  PyObject *my_id_capi = Py_None;
  int num_procs = 0;
  PyObject *num_procs_capi = Py_None;
  string folder = NULL;
  int slen(folder);
  PyObject *folder_capi = Py_None;
    static char *capi_kwlist[] = {"comm","my_id","num_procs","folder",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOO|O:fedrixs.ed_fsolver_intermediate",\
        capi_kwlist,&comm_capi,&my_id_capi,&num_procs_capi,&folder_capi))
        return NULL;
/*frompyobj*/
  /* Processing variable comm */
    f2py_success = int_from_pyobj(&comm,comm_capi,"fedrixs.ed_fsolver_intermediate() 1st argument (comm) can't be converted to int");
  if (f2py_success) {
  /* Processing variable my_id */
    f2py_success = int_from_pyobj(&my_id,my_id_capi,"fedrixs.ed_fsolver_intermediate() 2nd argument (my_id) can't be converted to int");
  if (f2py_success) {
  /* Processing variable num_procs */
    f2py_success = int_from_pyobj(&num_procs,num_procs_capi,"fedrixs.ed_fsolver_intermediate() 3rd argument (num_procs) can't be converted to int");
  if (f2py_success) {
  /* Processing variable folder */
  slen(folder) = -1;
  f2py_success = string_from_pyobj(&folder,&slen(folder),"",folder_capi,"string_from_pyobj failed in converting 1st keyword `folder' of fedrixs.ed_fsolver_intermediate to C string");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&comm,&my_id,&num_procs,folder,slen(folder));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    STRINGFREE(folder);
  }  /*if (f2py_success) of folder*/
  /* End of cleaning variable folder */
  } /*if (f2py_success) of num_procs*/
  /* End of cleaning variable num_procs */
  } /*if (f2py_success) of my_id*/
  /* End of cleaning variable my_id */
  } /*if (f2py_success) of comm*/
  /* End of cleaning variable comm */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/*********************** end of ed_fsolver_intermediate ***********************/

/******************************** xas_fsolver ********************************/
static char doc_f2py_rout_fedrixs_xas_fsolver[] = "\
xas_fsolver(comm,my_id,num_procs,[folder])\n\nWrapper for ``xas_fsolver``.\
\n\nParameters\n----------\n"
"comm : input int\n"
"my_id : input int\n"
"num_procs : input int\n"
"\nOther Parameters\n----------------\n"
"folder : input string(len=-1)";
/* extern void F_FUNC_US(xas_fsolver,XAS_FSOLVER)(int*,int*,int*,string,size_t); */
static PyObject *f2py_rout_fedrixs_xas_fsolver(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,string,size_t)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

  int comm = 0;
  PyObject *comm_capi = Py_None;
  int my_id = 0;
  PyObject *my_id_capi = Py_None;
  int num_procs = 0;
  PyObject *num_procs_capi = Py_None;
  string folder = NULL;
  int slen(folder);
  PyObject *folder_capi = Py_None;
    static char *capi_kwlist[] = {"comm","my_id","num_procs","folder",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOO|O:fedrixs.xas_fsolver",\
        capi_kwlist,&comm_capi,&my_id_capi,&num_procs_capi,&folder_capi))
        return NULL;
/*frompyobj*/
  /* Processing variable comm */
    f2py_success = int_from_pyobj(&comm,comm_capi,"fedrixs.xas_fsolver() 1st argument (comm) can't be converted to int");
  if (f2py_success) {
  /* Processing variable my_id */
    f2py_success = int_from_pyobj(&my_id,my_id_capi,"fedrixs.xas_fsolver() 2nd argument (my_id) can't be converted to int");
  if (f2py_success) {
  /* Processing variable num_procs */
    f2py_success = int_from_pyobj(&num_procs,num_procs_capi,"fedrixs.xas_fsolver() 3rd argument (num_procs) can't be converted to int");
  if (f2py_success) {
  /* Processing variable folder */
  slen(folder) = -1;
  f2py_success = string_from_pyobj(&folder,&slen(folder),"",folder_capi,"string_from_pyobj failed in converting 1st keyword `folder' of fedrixs.xas_fsolver to C string");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&comm,&my_id,&num_procs,folder,slen(folder));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    STRINGFREE(folder);
  }  /*if (f2py_success) of folder*/
  /* End of cleaning variable folder */
  } /*if (f2py_success) of num_procs*/
  /* End of cleaning variable num_procs */
  } /*if (f2py_success) of my_id*/
  /* End of cleaning variable my_id */
  } /*if (f2py_success) of comm*/
  /* End of cleaning variable comm */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/***************************** end of xas_fsolver *****************************/

/******************************** rixs_fsolver ********************************/
static char doc_f2py_rout_fedrixs_rixs_fsolver[] = "\
rixs_fsolver(comm,my_id,num_procs,[folder])\n\nWrapper for ``rixs_fsolver``.\
\n\nParameters\n----------\n"
"comm : input int\n"
"my_id : input int\n"
"num_procs : input int\n"
"\nOther Parameters\n----------------\n"
"folder : input string(len=-1)";
/* extern void F_FUNC_US(rixs_fsolver,RIXS_FSOLVER)(int*,int*,int*,string,size_t); */
static PyObject *f2py_rout_fedrixs_rixs_fsolver(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,string,size_t)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

  int comm = 0;
  PyObject *comm_capi = Py_None;
  int my_id = 0;
  PyObject *my_id_capi = Py_None;
  int num_procs = 0;
  PyObject *num_procs_capi = Py_None;
  string folder = NULL;
  int slen(folder);
  PyObject *folder_capi = Py_None;
    static char *capi_kwlist[] = {"comm","my_id","num_procs","folder",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOO|O:fedrixs.rixs_fsolver",\
        capi_kwlist,&comm_capi,&my_id_capi,&num_procs_capi,&folder_capi))
        return NULL;
/*frompyobj*/
  /* Processing variable comm */
    f2py_success = int_from_pyobj(&comm,comm_capi,"fedrixs.rixs_fsolver() 1st argument (comm) can't be converted to int");
  if (f2py_success) {
  /* Processing variable my_id */
    f2py_success = int_from_pyobj(&my_id,my_id_capi,"fedrixs.rixs_fsolver() 2nd argument (my_id) can't be converted to int");
  if (f2py_success) {
  /* Processing variable num_procs */
    f2py_success = int_from_pyobj(&num_procs,num_procs_capi,"fedrixs.rixs_fsolver() 3rd argument (num_procs) can't be converted to int");
  if (f2py_success) {
  /* Processing variable folder */
  slen(folder) = -1;
  f2py_success = string_from_pyobj(&folder,&slen(folder),"",folder_capi,"string_from_pyobj failed in converting 1st keyword `folder' of fedrixs.rixs_fsolver to C string");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&comm,&my_id,&num_procs,folder,slen(folder));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    STRINGFREE(folder);
  }  /*if (f2py_success) of folder*/
  /* End of cleaning variable folder */
  } /*if (f2py_success) of num_procs*/
  /* End of cleaning variable num_procs */
  } /*if (f2py_success) of my_id*/
  /* End of cleaning variable my_id */
  } /*if (f2py_success) of comm*/
  /* End of cleaning variable comm */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/**************************** end of rixs_fsolver ****************************/

/******************************* opavg_fsolver *******************************/
static char doc_f2py_rout_fedrixs_opavg_fsolver[] = "\
opavg_fsolver(comm,my_id,num_procs)\n\nWrapper for ``opavg_fsolver``.\
\n\nParameters\n----------\n"
"comm : input int\n"
"my_id : input int\n"
"num_procs : input int";
/* extern void F_FUNC_US(opavg_fsolver,OPAVG_FSOLVER)(int*,int*,int*); */
static PyObject *f2py_rout_fedrixs_opavg_fsolver(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

  int comm = 0;
  PyObject *comm_capi = Py_None;
  int my_id = 0;
  PyObject *my_id_capi = Py_None;
  int num_procs = 0;
  PyObject *num_procs_capi = Py_None;
    static char *capi_kwlist[] = {"comm","my_id","num_procs",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOO|:fedrixs.opavg_fsolver",\
        capi_kwlist,&comm_capi,&my_id_capi,&num_procs_capi))
        return NULL;
/*frompyobj*/
  /* Processing variable comm */
    f2py_success = int_from_pyobj(&comm,comm_capi,"fedrixs.opavg_fsolver() 1st argument (comm) can't be converted to int");
  if (f2py_success) {
  /* Processing variable my_id */
    f2py_success = int_from_pyobj(&my_id,my_id_capi,"fedrixs.opavg_fsolver() 2nd argument (my_id) can't be converted to int");
  if (f2py_success) {
  /* Processing variable num_procs */
    f2py_success = int_from_pyobj(&num_procs,num_procs_capi,"fedrixs.opavg_fsolver() 3rd argument (num_procs) can't be converted to int");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&comm,&my_id,&num_procs);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of num_procs*/
  /* End of cleaning variable num_procs */
  } /*if (f2py_success) of my_id*/
  /* End of cleaning variable my_id */
  } /*if (f2py_success) of comm*/
  /* End of cleaning variable comm */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/**************************** end of opavg_fsolver ****************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"ed_fsolver",-1,{{-1}},0,(char *)F_FUNC_US(ed_fsolver,ED_FSOLVER),(f2py_init_func)f2py_rout_fedrixs_ed_fsolver,doc_f2py_rout_fedrixs_ed_fsolver},
  {"ed_fsolver_intermediate",-1,{{-1}},0,(char *)F_FUNC_US(ed_fsolver_intermediate,ED_FSOLVER_INTERMEDIATE),(f2py_init_func)f2py_rout_fedrixs_ed_fsolver_intermediate,doc_f2py_rout_fedrixs_ed_fsolver_intermediate},
  {"xas_fsolver",-1,{{-1}},0,(char *)F_FUNC_US(xas_fsolver,XAS_FSOLVER),(f2py_init_func)f2py_rout_fedrixs_xas_fsolver,doc_f2py_rout_fedrixs_xas_fsolver},
  {"rixs_fsolver",-1,{{-1}},0,(char *)F_FUNC_US(rixs_fsolver,RIXS_FSOLVER),(f2py_init_func)f2py_rout_fedrixs_rixs_fsolver,doc_f2py_rout_fedrixs_rixs_fsolver},
  {"opavg_fsolver",-1,{{-1}},0,(char *)F_FUNC_US(opavg_fsolver,OPAVG_FSOLVER),(f2py_init_func)f2py_rout_fedrixs_opavg_fsolver,doc_f2py_rout_fedrixs_opavg_fsolver},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "fedrixs",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};

PyMODINIT_FUNC PyInit_fedrixs(void) {
  int i;
  PyObject *m,*d, *s, *tmp;
  m = fedrixs_module = PyModule_Create(&moduledef);
  Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module fedrixs (failed to import numpy)"); return m;}
  d = PyModule_GetDict(m);
  s = PyUnicode_FromString("1.21.2");
  PyDict_SetItemString(d, "__version__", s);
  Py_DECREF(s);
  s = PyUnicode_FromString(
    "This module 'fedrixs' is auto-generated with f2py (version:1.21.2).\nFunctions:\n"
"  ed_fsolver(comm,my_id,num_procs,folder='')\n"
"  ed_fsolver_intermediate(comm,my_id,num_procs,folder='')\n"
"  xas_fsolver(comm,my_id,num_procs,folder='')\n"
"  rixs_fsolver(comm,my_id,num_procs,folder='')\n"
"  opavg_fsolver(comm,my_id,num_procs)\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  Py_DECREF(s);
  s = PyUnicode_FromString("1.21.2");
  PyDict_SetItemString(d, "__f2py_numpy_version__", s);
  Py_DECREF(s);
  fedrixs_error = PyErr_NewException ("fedrixs.error", NULL, NULL);
  /*
   * Store the error object inside the dict, so that it could get deallocated.
   * (in practice, this is a module, so it likely will not and cannot.)
   */
  PyDict_SetItemString(d, "_fedrixs_error", fedrixs_error);
  Py_DECREF(fedrixs_error);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
    tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
    PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
    Py_DECREF(tmp);
  }





/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"fedrixs");
#endif
  return m;
}
#ifdef __cplusplus
}
#endif
